name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache
      uses: actions/cache@v2.1.5
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ~/.m2
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-${{ hashFiles('pom.xml') }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
